<?php
require("include/dbinfo.php");
$link=mysqli_connect($server,$user,$pass)or die(errorReport(mysqli_error()));
mysqli_select_db($link, $db)or die(errorReport(mysqli_error()));
mysqli_query($link, "insert into Departments values (\"IT Department\",\"68\",\"IT\", 600);");
mysqli_query($link, "insert into Departments values (\"Cardiology\",\" 15\",\"CR\", 500);");
mysqli_query($link, "insert into Departments values (\"Maternity\",\" 23\",\"MT\", 400);");
mysqli_query($link, "insert into Departments values (\"Neurology\",\" 8\",\"NE\", 300);");
mysqli_query($link, "insert into Departments values (\"Pharmacy\",\" 5\",\"PH\", 200);");
mysqli_query($link, "insert into Departments values (\"Orthopaedics\",\" 1\",\"OR\", 100);");
mysqli_query($link, "insert into Employee values (\"101\",\"Andrew\",\"Delhi\",\"1987-01-02\",null,\"Male\",20000,\"Doctor\",\"IT\");");
mysqli_query($link, "insert into Employee values (\"1001\",\"Mike\",\"Jaipur\",\"1984-09-02\",null,\"Male\",20000,\"Doctor\",\"CR\");");
mysqli_query($link, "insert into Employee values (\"1002\",\"Avril\",\London\",\"1983-11-02\",null,\"Female\",20000,null,\"CR\");");
mysqli_query($link, "insert into Employee values (\"2001\",\"Thomas\",\"UK\",\"1988-10-02\",null,\"Male\",20000,null,\"MT\");");
mysqli_query($link, "insert into Employee values (\"3001\",\"Stefen\",\"New York\",\"1977-01-02\",null,\"Male\",20000,null,\"NE\");");
mysqli_query($link, "insert into Employee values (\"4001\",\"Mary\",\"Delhi\",\"1969-02-02\",null,\"Female\",20000,null,\"PH\");");
mysqli_query($link, "insert into Employee values (\"4002\",\"Eppes\",\"Delhi\",\"1976-03-02\",null,\"Male\",20000,null,\"PH\");");
mysqli_query($link, "insert into Employee values (\"2002\",\"Ross\",\"Delhi\",\"1984-06-02\",null,\"Female\",20000,null,\"MT\");");
mysqli_query($link, "insert into Employee values (\"1003\",\"David\",\"Delhi\",\"1980-06-02\",null,\"Male\",20000,null,\"CR\");");
mysqli_query($link, "insert into Employee values (\"6802\",\"John\",\"Delhi\",\"19890-08-02\",null,\"Male\",20000,null,\"IT\");");
mysqli_query($link, "insert into Patients values (\"P001\",\"Charles Mathew\",\"Delhi\",\"1987-01-02\",null,\"Male\",\"B+\");");
mysqli_query($link, "insert into Patients values (\"P002\",\"Micheal Scofield\",\"New Delhi\",\"1988-04-02\",null,\"Male\",\"AB+\");");
mysqli_query($link, "insert into Patients values (\"P003\",\"Charles Mathew Scofield\",\"New Delhi\",\"1988-04-02\",null,\"Male\",\"AB+\");");
mysqli_query($link, "insert into Patients values (\"P004\",\"Peter Edward Scofield\",\"Jaipur\",\"1980-04-02\",null,\"Male\",\"A+\");");
mysqli_query($link, "insert into Patients values (\"P005\",\"Robert Brown\",\"Goa\",\"1980-08-22\",null,\"Male\",\"A-\");");
mysqli_query($link, "insert into Passwords values (\"ITS6801\",\"ITS6801\");");
mysqli_query($link, "insert into Room values (\"Z1\",\"GEN\",\"0267\",2500.00,\"P005\");");
mysqli_query($link, "insert into Room values (\"Z2\",\"PRI\",\"0141\",5000.00,\"P002\");");
mysqli_query($link, "insert into Room values (\"Z3\",\"ICU\",\"0581\",2500.00,\"P001\");");
mysqli_query($link, "insert into Room values (\"Z4\",\"ICU\",\"0582\",2500.00,\"P003\");");
mysqli_query($link, "insert into Room values (\"Z5\",\"PRI\",\"0142\",2500.00,null);");
mysqli_query($link, "insert into Room values (\"Z6\",\"GEN\",\"0268\",2500.00,null);");
?>
